### ISSUE TITLE
Web3Modal example

### ISSUE THREAD

**Issue by anstak** [ByteAtATime/wagmi-svelte#1]
Hello! Thank you for great job! Do you use it for real project? Do you have example with web3modal or something else?

**Comment by ByteAtATime** [comment]
Hey! Sorry for the late response. I currently do not have any projects using this, although some are in development. Are you interested in an integration with Web3Modal? If so, I may have to do some research before getting back to you.

Thanks for your interest!

**Comment by anstak** [comment]
I have real project using Next.js, wagmi and rainbowkit. And that is great toolkit, but I like svelte more than react, so I cant find something like rainbowkit or web3modal for svelte with wagmi. If you will be create some toolkit for real project, thats will be super.

**Comment by ByteAtATime** [comment]
So I did some snooping around, and there seems to [already be an example of using Web3Modal with Svelte](https://github.com/WalletConnect/web-examples/tree/main/dapps/web3modal/svelte/). If you have anything specific you're looking for, feel free to ask, but as of current I see dimishing returns in creating a Svelte-specific library. (Web3Modal uses web components, which are universal.)

I will close this for now, but will continue looking into the possibility of a Svelte RainbowKit.
